### ISSUE TITLE
utils文件下mask_to_semantic 是什么意思

### ISSUE THREAD

**Issue by zhaotongdong** [JasmineRain/NAIC_AI-RS#1]
你好，请问下这个utils.py文件下mask_to_semantic 是什么意思

**Comment by JasmineRain** [comment]
把单通道的mask标签转换为多通道的one-hot训练标签

**Comment by JasmineRain** [comment]
> 你好，请问下这个utils.py文件下mask_to_semantic 是什么意思

把单通道的mask标签转换为多通道的one-hot训练标签

**Comment by zhaotongdong** [comment]
@JasmineRain edge这个参数是什么意思呀，为什么要进行这个操作

**Comment by JasmineRain** [comment]
> @JasmineRain edge这个参数是什么意思呀，为什么要进行这个操作

那个是Label smooth的时候用的，edge=True代表使用边缘标签平滑策略

**Comment by zhaotongdong** [comment]
@JasmineRain 边缘标签平滑是什么意思，为什么要进行边缘标签平滑那，可能我的问题有点蠢。。。

**Comment by JasmineRain** [comment]
你看代码就知道了   大部分标注不准确集中在不同类的交界处    类中心区域标签基本是正确的

**Comment by zhaotongdong** [comment]
@JasmineRain 好的，非常感谢
